name: CI

on: [push, pull_request]

jobs:
  test-code:
    name : test ${{ matrix.os }} / ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install Visual C++ Build Tools (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2019buildtools --version=16.11 -y
          choco install visualstudio2019-workload-vctools -y

      - name: Add Anaconda PyPI for llvmlite (macOS)
        if: runner.os == 'macOS'
        run: |
          poetry source add --priority=explicit numba https://pypi.anaconda.org/numba/label/wheels/simple
          poetry add --source numba llvmlite

      - name: Run ci
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --without docs
          make ci
